name: CodeQL

on:
  pull_request:
  schedule:
    - cron: '0 9 * * 4'

jobs:
  Analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v3
      with:
        languages: javascript
        config-file: ./.github/codeql-config.yml
      
    - uses: github/codeql-action/analyze@v3
