name: CI

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v3
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint --if-present
