name: Diagrams

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.md'
      - '**/workflows/DIAGRAMS.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reasone for Manual Build'
        required: false
        default: '🧩'

jobs:
  Diagrams:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event.inputs.reason }}"
    - uses: actions/checkout@v4
    - uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: examples/*.md
        output: diagrams/
    - uses: actions/upload-artifact@v4
      with:
        name: example/*.svg
        path: diagrams/
